[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[dependency-groups]
dev = [
    "django-stubs>=5.1.1",
    "ruff>=0.8.2",
]

[project]
name = "djls-agent"
version = "0.1.0"
description = "Python agent for django-language-server"
readme = "README.md"
authors = [
    { name = "Josh Thomas", email = "josh@joshthomas.dev" }
]
requires-python = ">=3.9"
dependencies = [
    "django>=4.2",
    "protobuf>=5.29.1",
]

[tool.hatch.build]
packages = ["src/djls_agent"]
