[tagspecs.django.template.defaulttags.autoescape]
end = { tag = "endautoescape" }

[tagspecs.django.template.defaulttags.block]
end = { tag = "endblock" }

[tagspecs.django.template.defaulttags.comment]
end = { tag = "endcomment" }

[tagspecs.django.template.defaulttags.filter]
end = { tag = "endfilter" }

[tagspecs.django.template.defaulttags.for]
end = { tag = "endfor" }
intermediates = [ "empty" ]

[tagspecs.django.template.defaulttags.if]
end = { tag = "endif" }
intermediates = [ "elif", "else" ]

[tagspecs.django.template.defaulttags.ifchanged]
end = { tag = "endifchanged" }
intermediates = [ "else" ]

[tagspecs.django.template.defaulttags.spaceless]
end = { tag = "endspaceless" }

[tagspecs.django.template.defaulttags.verbatim]
end = { tag = "endverbatim" }

[tagspecs.django.template.defaulttags.with]
end = { tag = "endwith" }

[tagspecs.django.templatetags.cache.cache]
end = { tag = "endcache" }

[tagspecs.django.templatetags.i10n.localize]
end = { tag = "endlocalize" }

[tagspecs.django.templatetags.i18n.blocktranslate]
end = { tag = "endblocktranslate" }
intermediates = [ "plural" ]

[tagspecs.django.templatetags.tz.localtime]
end = { tag = "endlocaltime" }

[tagspecs.django.templatetags.tz.timezone]
end = { tag = "endtimezone" }
