rules:
  cache-poisoning:
    ignore:
      # test workflow does not produce artifacts to poison
      - test.yml
      # all caching is disabled when a tag is pushed
      - build.yml:94:9
      - build.yml:104:9
      - build.yml:114:9
      - build.yml:124:9
      - build.yml:130:9
      - build.yml:244:9
      - build.yml:277:9
      - build.yml:310:9
      - build.yml:320:9
      - build.yml:331:9
      - build.yml:364:9
      - build.yml:374:9
      - build.yml:385:9
