rules:
  cache-poisoning:
    ignore:
      # test workflow does not produce artifacts to poison
      - test.yml
      # all caching is disabled when a tag is pushed
      - build.yml:94:9
      - build.yml:104:9
      - build.yml:114:9
      - build.yml:123:9
      - build.yml:129:9
      - build.yml:243:9
      - build.yml:276:9
      - build.yml:309:9
      - build.yml:319:9
      - build.yml:330:9
      - build.yml:363:9
      - build.yml:373:9
      - build.yml:384:9
