rules:
  cache-poisoning:
    ignore:
      # test workflow does not produce artifacts to poison
      - test.yml
      # all caching is disabled when a tag is pushed
      - build.yml:87:9
      - build.yml:97:9
      - build.yml:106:9
      - build.yml:113:9
      - build.yml:227:9
      - build.yml:259:9
      - build.yml:290:9
      - build.yml:300:9
      - build.yml:312:9
      - build.yml:343:9
      - build.yml:353:9
      - build.yml:365:9
