rules:
  cache-poisoning:
    ignore:
      # test workflow does not produce artifacts to poison
      - test.yml
      # all caching is disabled when a tag is pushed
      - build.yml:94:9
      - build.yml:104:9
      - build.yml:112:9
      - build.yml:120:9
      - build.yml:234:9
      - build.yml:267:9
      - build.yml:300:9
      - build.yml:310:9
      - build.yml:321:9
      - build.yml:354:9
      - build.yml:364:9
      - build.yml:375:9
