# Django built-in template tags
[django.template.defaulttags.if]
branches = ["elif", "else"]
closing = "endif"
type = "block"

[[django.template.defaulttags.if.args]]
name = "condition"
required = true

[django.template.defaulttags.for]
branches = ["empty"]
closing = "endfor"
type = "block"

[[django.template.defaulttags.for.args]]
name = "{item}"
required = true

[[django.template.defaulttags.for.args]]
name = "in"
required = true

[[django.template.defaulttags.for.args]]
name = "{iterable}"
required = true

[django.template.defaulttags.block]
closing = "endblock"
type = "block"
