[django.template.defaulttags.block]
closing = "endblock"
type = "block"

[django.template.defaulttags.for]
branches = ["empty"]
closing = "endfor"
type = "block"
args = [
  { name = "{item}", required = true },
  { name = "in", required = true },
  { name = "{iterable}", required = true },
]

[django.template.defaulttags.if]
branches = ["elif", "else"]
closing = "endif"
type = "block"
args = [{ name = "condition", required = true }]
