[django.template.defaulttags.if]
type = "block"
closing = "endif"

# We keep the intermediates field name in TOML since we're using serde rename
# to map it to branches in the Rust code
[[django.template.defaulttags.if.intermediates]]
name = "elif"
args = true

[[django.template.defaulttags.if.intermediates]]
name = "else"
args = false

[[django.template.defaulttags.if.args]]
name = "condition"
required = true

[django.template.defaulttags.for]
type = "block"
closing = "endfor"

# We keep the intermediates field name in TOML since we're using serde rename
# to map it to branches in the Rust code
[[django.template.defaulttags.for.intermediates]]
name = "empty"
args = false

[[django.template.defaulttags.for.args]]
name = "{item}"
required = true

[[django.template.defaulttags.for.args]]
name = "in"
required = true

[[django.template.defaulttags.for.args]]
name = "{iterable}"
required = true
