[package]
name = "djls-ipc"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

tempfile = "3.14.0"

[target.'cfg(windows)'.dependencies]
uuid = { version = "1.11.0", features = ["fast-rng"] }
