[package]
name = "djls-django"
version = "0.0.0"
edition = "2021"

[dependencies]
djls-ipc = { workspace = true }
djls-python = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
