use camino::Utf8Path;
use serde::Deserialize;
use serde::Serialize;

const HEADER: &str = "# Auto-generated by `djls-corpus bump`. Do not edit.\n\n";

#[derive(Debug, Default, Serialize, Deserialize)]
pub struct Lockfile {
    #[serde(default, rename = "package")]
    pub packages: Vec<LockedPackage>,
    #[serde(default, rename = "repo")]
    pub repos: Vec<LockedRepo>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LockedPackage {
    pub name: String,
    pub version: String,
    pub resolved: String,
    pub url: String,
    pub sha256: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LockedRepo {
    pub name: String,
    pub url: String,
    pub tag: String,
    #[serde(rename = "ref")]
    pub git_ref: String,
}

impl Lockfile {
    pub fn load(path: &Utf8Path) -> anyhow::Result<Self> {
        let content = std::fs::read_to_string(path.as_std_path())?;
        let lockfile: Self = toml::from_str(&content)?;
        Ok(lockfile)
    }

    pub fn save(&self, path: &Utf8Path) -> anyhow::Result<()> {
        let content = toml::to_string_pretty(self)?;
        std::fs::write(path.as_std_path(), format!("{HEADER}{content}"))?;
        Ok(())
    }
}
