use std::collections::HashMap;
use std::time::Duration;

use camino::Utf8Path;
use serde::Deserialize;
use serde::Serialize;

use crate::manifest::Manifest;
use crate::manifest::Repo;

const HEADER: &str = "# Auto-generated by `djls-corpus lock`. Do not edit.\n\n";

#[derive(Debug, Default, Serialize, Deserialize)]
pub struct Lockfile {
    #[serde(default, rename = "repo")]
    pub repos: Vec<LockedRepo>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LockedRepo {
    pub name: String,
    pub url: String,
    pub tag: String,
    #[serde(rename = "ref")]
    pub git_ref: String,
}

impl Lockfile {
    pub fn load(path: &Utf8Path) -> anyhow::Result<Self> {
        let content = std::fs::read_to_string(path.as_std_path())?;
        let lockfile: Self = toml::from_str(&content)?;
        Ok(lockfile)
    }

    pub fn save(&self, path: &Utf8Path) -> anyhow::Result<()> {
        let content = toml::to_string_pretty(self)?;
        std::fs::write(path.as_std_path(), format!("{HEADER}{content}"))?;
        Ok(())
    }
}

pub enum LockFilter {
    All,
    Names(Vec<String>),
}

impl LockFilter {
    fn matches(&self, name: &str) -> bool {
        match self {
            LockFilter::All => true,
            LockFilter::Names(names) => names.iter().any(|n| n.eq_ignore_ascii_case(name)),
        }
    }
}

pub fn lock_corpus(
    manifest: &Manifest,
    existing: &Lockfile,
    filter: &LockFilter,
    licenses_dir: &Utf8Path,
) -> anyhow::Result<(Lockfile, Vec<String>)> {
    let client = reqwest::blocking::Client::builder()
        .timeout(Duration::from_secs(60))
        .user_agent("djls-corpus")
        .build()?;

    std::fs::create_dir_all(licenses_dir.as_std_path())?;

    let existing_repos: HashMap<&str, &LockedRepo> = existing
        .repos
        .iter()
        .map(|r| (r.name.as_str(), r))
        .collect();

    let mut repos = Vec::new();
    let mut errors = Vec::new();

    for repo in &manifest.repos {
        if !filter.matches(&repo.name) {
            if let Some(locked) = existing_repos.get(repo.name.as_str()) {
                repos.push((*locked).clone());
            }
            continue;
        }

        match resolve_repo(
            &client,
            repo,
            existing_repos.get(repo.name.as_str()).copied(),
            licenses_dir,
        ) {
            Ok(locked) => repos.push(locked),
            Err(e) => {
                tracing::error!(name = repo.name, error = %e, "failed to resolve repo");
                errors.push(format!("{}: {e}", repo.name));
                if let Some(locked) = existing_repos.get(repo.name.as_str()) {
                    repos.push((*locked).clone());
                }
            }
        }
    }

    // Remove license files for repos no longer in the manifest
    if matches!(filter, LockFilter::All) {
        let locked_names: std::collections::HashSet<&str> =
            repos.iter().map(|r| r.name.as_str()).collect();
        if let Ok(entries) = std::fs::read_dir(licenses_dir.as_std_path()) {
            for entry in entries.filter_map(Result::ok) {
                let Some(name) = entry.file_name().to_str().map(String::from) else {
                    continue;
                };
                if !locked_names.contains(name.as_str()) {
                    let _ = std::fs::remove_file(entry.path());
                }
            }
        }
    }

    Ok((Lockfile { repos }, errors))
}

fn resolve_repo(
    client: &reqwest::blocking::Client,
    repo: &Repo,
    existing: Option<&LockedRepo>,
    licenses_dir: &Utf8Path,
) -> anyhow::Result<LockedRepo> {
    let (tag, git_ref) = match &repo.git_ref {
        Some(r) if looks_like_sha(r) => (r.clone(), r.clone()),
        Some(r) => resolve_ref(&repo.url, r)?,
        None => resolve_latest_tag(&repo.url)?,
    };

    let license_path = licenses_dir.join(&repo.name);

    match existing {
        Some(prev) if prev.git_ref == git_ref && license_path.exists() => {
            let short = git_ref.get(..12).unwrap_or(&git_ref);
            tracing::info!(name = repo.name, tag, git_ref = short, "current");
        }
        Some(prev) if prev.git_ref == git_ref => {
            let short = git_ref.get(..12).unwrap_or(&git_ref);
            tracing::info!(
                name = repo.name,
                tag,
                git_ref = short,
                "current (fetching license)"
            );
            let text = fetch_license_text(client, &repo.url, &git_ref);
            write_license_file(&license_path, text.as_deref());
        }
        Some(prev) => {
            let old_short = prev.git_ref.get(..12).unwrap_or(&prev.git_ref);
            let new_short = git_ref.get(..12).unwrap_or(&git_ref);
            tracing::info!(
                name = repo.name,
                from = format!("{} ({old_short})", prev.tag),
                to = format!("{tag} ({new_short})"),
                "updated"
            );
            let text = fetch_license_text(client, &repo.url, &git_ref);
            write_license_file(&license_path, text.as_deref());
        }
        None => {
            let short = git_ref.get(..12).unwrap_or(&git_ref);
            tracing::info!(name = repo.name, tag, git_ref = short, "new");
            let text = fetch_license_text(client, &repo.url, &git_ref);
            write_license_file(&license_path, text.as_deref());
        }
    }

    Ok(LockedRepo {
        name: repo.name.clone(),
        url: repo.url.clone(),
        tag,
        git_ref,
    })
}

fn write_license_file(path: &Utf8Path, text: Option<&str>) {
    if let Some(text) = text {
        if let Err(e) = std::fs::write(path.as_std_path(), text) {
            tracing::warn!(path = %path, error = %e, "failed to write license file");
        }
    }
}

fn looks_like_sha(s: &str) -> bool {
    s.len() >= 40 && s.chars().all(|c| c.is_ascii_hexdigit())
}

fn parse_tag_version(tag: &str) -> Option<(Vec<u32>, bool)> {
    let s = tag.strip_prefix('v').unwrap_or(tag);
    let mut parts = Vec::new();
    let mut is_prerelease = false;

    for segment in s.split('.') {
        let numeric: String = segment.chars().take_while(char::is_ascii_digit).collect();
        if numeric.is_empty() {
            if parts.is_empty() {
                return None;
            }
            break;
        }
        parts.push(numeric.parse::<u32>().ok()?);
        if numeric.len() < segment.len() {
            is_prerelease = true;
        }
    }

    if parts.is_empty() {
        return None;
    }

    Some((parts, is_prerelease))
}

/// Resolve a named ref (branch or tag) to `(label, commit_sha)`.
fn resolve_ref(url: &str, git_ref: &str) -> anyhow::Result<(String, String)> {
    let output = std::process::Command::new("git")
        .args(["ls-remote", url, git_ref, &format!("{git_ref}^{{}}")])
        .output()
        .map_err(|e| {
            if e.kind() == std::io::ErrorKind::NotFound {
                anyhow::anyhow!("git not found — install git to resolve repo refs")
            } else {
                anyhow::anyhow!("Failed to run git ls-remote: {e}")
            }
        })?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!("git ls-remote failed for {url}: {stderr}");
    }

    let stdout = String::from_utf8(output.stdout)?;
    let mut sha = None;
    let mut dereferenced = false;

    for line in stdout.lines() {
        let Some((line_sha, refname)) = line.split_once('\t') else {
            continue;
        };
        // Prefer ^{} (dereferenced annotated tag → commit SHA)
        if refname.ends_with("^{}") {
            sha = Some(line_sha.to_string());
            dereferenced = true;
        } else if !dereferenced {
            sha = Some(line_sha.to_string());
        }
    }

    let sha = sha.ok_or_else(|| anyhow::anyhow!("Ref {git_ref:?} not found in {url}"))?;
    Ok((git_ref.to_string(), sha))
}

fn resolve_latest_tag(url: &str) -> anyhow::Result<(String, String)> {
    let output = std::process::Command::new("git")
        .args(["ls-remote", "--tags", url])
        .output()
        .map_err(|e| {
            if e.kind() == std::io::ErrorKind::NotFound {
                anyhow::anyhow!("git not found — install git to resolve repo tags")
            } else {
                anyhow::anyhow!("Failed to run git ls-remote: {e}")
            }
        })?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!("git ls-remote failed for {url}: {stderr}");
    }

    let stdout = String::from_utf8(output.stdout)?;

    // Collect tag → SHA, preferring ^{} (dereferenced) for annotated tags
    let mut tags: HashMap<String, String> = HashMap::new();

    for line in stdout.lines() {
        let Some((sha, refname)) = line.split_once('\t') else {
            continue;
        };
        let Some(tag) = refname.strip_prefix("refs/tags/") else {
            continue;
        };

        if let Some(base_tag) = tag.strip_suffix("^{}") {
            tags.insert(base_tag.to_string(), sha.to_string());
        } else if !tags.contains_key(tag) {
            tags.insert(tag.to_string(), sha.to_string());
        }
    }

    if tags.is_empty() {
        anyhow::bail!("No tags found for {url}");
    }

    // Sort by parsed version: highest first, stable before pre-release
    let mut versioned: Vec<(Vec<u32>, bool, String, String)> = tags
        .iter()
        .filter_map(|(tag, sha)| {
            parse_tag_version(tag).map(|(parts, pre)| (parts, pre, tag.clone(), sha.clone()))
        })
        .collect();

    versioned.sort_by(|a, b| {
        a.0.cmp(&b.0).reverse().then(a.1.cmp(&b.1)) // false (stable) < true (pre-release)
    });

    if let Some((_, _, tag, sha)) = versioned.into_iter().next() {
        return Ok((tag, sha));
    }

    // No version-like tags; pick first alphabetically
    let mut entries: Vec<_> = tags.into_iter().collect();
    entries.sort_by(|a, b| a.0.cmp(&b.0));
    let (tag, sha) = entries.into_iter().next().unwrap();
    Ok((tag, sha))
}

const LICENSE_BASENAMES: &[&str] = &["LICENSE", "LICENCE", "COPYING"];
const LICENSE_EXTENSIONS: &[&str] = &["", ".md", ".txt", ".rst"];

/// Fetch the license file text for a repo at the given ref by trying
/// common license filenames against the host's raw content URL.
fn fetch_license_text(
    client: &reqwest::blocking::Client,
    url: &str,
    git_ref: &str,
) -> Option<String> {
    let (host, path) = parse_git_host(url)?;

    for name in LICENSE_BASENAMES.iter().flat_map(|base| {
        LICENSE_EXTENSIONS
            .iter()
            .map(move |ext| format!("{base}{ext}"))
    }) {
        let raw_url = match &host {
            GitHost::GitHub => {
                format!("https://raw.githubusercontent.com/{path}/{git_ref}/{name}")
            }
            GitHost::GitLab(domain) => {
                format!("https://{domain}/{path}/-/raw/{git_ref}/{name}")
            }
        };

        if let Ok(resp) = client.get(&raw_url).send() {
            if resp.status().is_success() {
                if let Ok(text) = resp.text() {
                    if !text.is_empty() {
                        return Some(text);
                    }
                }
            }
        }
    }

    None
}

enum GitHost<'a> {
    GitHub,
    GitLab(&'a str),
}

/// Parse a git URL into its host kind and `owner/repo` path.
fn parse_git_host(url: &str) -> Option<(GitHost<'_>, &str)> {
    let after_scheme = url
        .strip_prefix("https://")
        .or_else(|| url.strip_prefix("http://"))?;

    let (host, path) = after_scheme.split_once('/')?;
    let path = path.trim_end_matches(".git");

    if path.is_empty() {
        return None;
    }

    if host == "github.com" {
        // Require at least owner/repo
        if path.contains('/') && !path.ends_with('/') {
            return Some((GitHost::GitHub, path));
        }
        return None;
    }

    if host == "gitlab.com" || host.starts_with("gitlab.") {
        return Some((GitHost::GitLab(host), path));
    }

    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_tag_version_simple() {
        assert_eq!(parse_tag_version("v1.0.0"), Some((vec![1, 0, 0], false)));
        assert_eq!(parse_tag_version("1.0.0"), Some((vec![1, 0, 0], false)));
    }

    #[test]
    fn parse_tag_version_prerelease() {
        assert_eq!(parse_tag_version("v0.8.6rc1"), Some((vec![0, 8, 6], true)));
        assert_eq!(parse_tag_version("v5.2a1"), Some((vec![5, 2], true)));
    }

    #[test]
    fn parse_tag_version_not_a_version() {
        assert_eq!(parse_tag_version("release-candidate"), None);
        assert_eq!(parse_tag_version("nightly"), None);
    }

    #[test]
    fn parse_git_host_github() {
        let (host, path) = parse_git_host("https://github.com/getsentry/sentry.git").unwrap();
        assert!(matches!(host, GitHost::GitHub));
        assert_eq!(path, "getsentry/sentry");
    }

    #[test]
    fn parse_git_host_github_no_dot_git() {
        let (host, path) = parse_git_host("https://github.com/django/djangoproject.com").unwrap();
        assert!(matches!(host, GitHost::GitHub));
        assert_eq!(path, "django/djangoproject.com");
    }

    #[test]
    fn parse_git_host_gitlab_com() {
        let (host, path) = parse_git_host("https://gitlab.com/group/project.git").unwrap();
        assert!(matches!(host, GitHost::GitLab("gitlab.com")));
        assert_eq!(path, "group/project");
    }

    #[test]
    fn parse_git_host_gitlab_self_hosted() {
        let (host, path) = parse_git_host("https://gitlab.example.com/team/project.git").unwrap();
        assert!(matches!(host, GitHost::GitLab("gitlab.example.com")));
        assert_eq!(path, "team/project");
    }

    #[test]
    fn parse_git_host_unknown() {
        assert!(parse_git_host("https://codeberg.org/user/project.git").is_none());
    }
}
