# WARNING: This file is generated by protobuf. DO NOT EDIT!
# Any changes made to this file will be overwritten when the protobuf files are regenerated.
# Source: v1/check.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar, Optional as _Optional

DESCRIPTOR: _descriptor.FileDescriptor

class HealthRequest(_message.Message):
    __slots__ = ()
    def __init__(self) -> None: ...

class HealthResponse(_message.Message):
    __slots__ = ("passed", "error")
    PASSED_FIELD_NUMBER: _ClassVar[int]
    ERROR_FIELD_NUMBER: _ClassVar[int]
    passed: bool
    error: str
    def __init__(self, passed: bool = ..., error: _Optional[str] = ...) -> None: ...

class AppInstalledRequest(_message.Message):
    __slots__ = ("app_name",)
    APP_NAME_FIELD_NUMBER: _ClassVar[int]
    app_name: str
    def __init__(self, app_name: _Optional[str] = ...) -> None: ...

class AppInstalledResponse(_message.Message):
    __slots__ = ("passed", "error")
    PASSED_FIELD_NUMBER: _ClassVar[int]
    ERROR_FIELD_NUMBER: _ClassVar[int]
    passed: bool
    error: str
    def __init__(self, passed: bool = ..., error: _Optional[str] = ...) -> None: ...
