# WARNING: This file is generated by protobuf. DO NOT EDIT!
# Any changes made to this file will be overwritten when the protobuf files are regenerated.
# Source: v1/commands.proto

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/commands.proto
# Protobuf Python Version: 5.29.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    1,
    '',
    'v1/commands.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import django_pb2 as v1_dot_django__pb2
from . import python_pb2 as v1_dot_python__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11v1/commands.proto\x12\x10\x64jls.v1.commands\x1a\x0fv1/django.proto\x1a\x0fv1/python.proto\"\xbd\x01\n\x05\x43heck\x1a\x0f\n\rHealthRequest\x1a>\n\x0eHealthResponse\x12\x0e\n\x06passed\x18\x01 \x01(\x08\x12\x12\n\x05\x65rror\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_error\x1a\x19\n\x17GeoDjangoPrereqsRequest\x1aH\n\x18GeoDjangoPrereqsResponse\x12\x0e\n\x06passed\x18\x01 \x01(\x08\x12\x12\n\x05\x65rror\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_error\"c\n\x06Python\x1a\x17\n\x15GetEnvironmentRequest\x1a@\n\x16GetEnvironmentResponse\x12&\n\x06python\x18\x01 \x01(\x0b\x32\x16.djls.v1.python.Python\"e\n\x06\x44jango\x1a\x17\n\x15GetProjectInfoRequest\x1a\x42\n\x16GetProjectInfoResponse\x12(\n\x07project\x18\x01 \x01(\x0b\x32\x17.djls.v1.django.Projectb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.commands_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECK']._serialized_start=74
  _globals['_CHECK']._serialized_end=263
  _globals['_CHECK_HEALTHREQUEST']._serialized_start=83
  _globals['_CHECK_HEALTHREQUEST']._serialized_end=98
  _globals['_CHECK_HEALTHRESPONSE']._serialized_start=100
  _globals['_CHECK_HEALTHRESPONSE']._serialized_end=162
  _globals['_CHECK_GEODJANGOPREREQSREQUEST']._serialized_start=164
  _globals['_CHECK_GEODJANGOPREREQSREQUEST']._serialized_end=189
  _globals['_CHECK_GEODJANGOPREREQSRESPONSE']._serialized_start=191
  _globals['_CHECK_GEODJANGOPREREQSRESPONSE']._serialized_end=263
  _globals['_PYTHON']._serialized_start=265
  _globals['_PYTHON']._serialized_end=364
  _globals['_PYTHON_GETENVIRONMENTREQUEST']._serialized_start=275
  _globals['_PYTHON_GETENVIRONMENTREQUEST']._serialized_end=298
  _globals['_PYTHON_GETENVIRONMENTRESPONSE']._serialized_start=300
  _globals['_PYTHON_GETENVIRONMENTRESPONSE']._serialized_end=364
  _globals['_DJANGO']._serialized_start=366
  _globals['_DJANGO']._serialized_end=467
  _globals['_DJANGO_GETPROJECTINFOREQUEST']._serialized_start=376
  _globals['_DJANGO_GETPROJECTINFOREQUEST']._serialized_end=399
  _globals['_DJANGO_GETPROJECTINFORESPONSE']._serialized_start=401
  _globals['_DJANGO_GETPROJECTINFORESPONSE']._serialized_end=467
# @@protoc_insertion_point(module_scope)
