# WARNING: This file is generated by protobuf. DO NOT EDIT!
# Any changes made to this file will be overwritten when the protobuf files are regenerated.
# Source: v1/messages.proto

from . import check_pb2 as _check_pb2
from . import django_pb2 as _django_pb2
from . import python_pb2 as _python_pb2
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar, Mapping as _Mapping, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class Request(_message.Message):
    __slots__ = ("check__health", "check__geodjango_prereqs", "python__get_environment", "django__get_project_info")
    CHECK__HEALTH_FIELD_NUMBER: _ClassVar[int]
    CHECK__GEODJANGO_PREREQS_FIELD_NUMBER: _ClassVar[int]
    PYTHON__GET_ENVIRONMENT_FIELD_NUMBER: _ClassVar[int]
    DJANGO__GET_PROJECT_INFO_FIELD_NUMBER: _ClassVar[int]
    check__health: _check_pb2.HealthRequest
    check__geodjango_prereqs: _check_pb2.GeoDjangoPrereqsRequest
    python__get_environment: _python_pb2.GetEnvironmentRequest
    django__get_project_info: _django_pb2.GetProjectInfoRequest
    def __init__(self, check__health: _Optional[_Union[_check_pb2.HealthRequest, _Mapping]] = ..., check__geodjango_prereqs: _Optional[_Union[_check_pb2.GeoDjangoPrereqsRequest, _Mapping]] = ..., python__get_environment: _Optional[_Union[_python_pb2.GetEnvironmentRequest, _Mapping]] = ..., django__get_project_info: _Optional[_Union[_django_pb2.GetProjectInfoRequest, _Mapping]] = ...) -> None: ...

class Response(_message.Message):
    __slots__ = ("check__health", "check__geodjango_prereqs", "python__get_environment", "django__get_project_info", "error")
    CHECK__HEALTH_FIELD_NUMBER: _ClassVar[int]
    CHECK__GEODJANGO_PREREQS_FIELD_NUMBER: _ClassVar[int]
    PYTHON__GET_ENVIRONMENT_FIELD_NUMBER: _ClassVar[int]
    DJANGO__GET_PROJECT_INFO_FIELD_NUMBER: _ClassVar[int]
    ERROR_FIELD_NUMBER: _ClassVar[int]
    check__health: _check_pb2.HealthResponse
    check__geodjango_prereqs: _check_pb2.GeoDjangoPrereqsResponse
    python__get_environment: _python_pb2.GetEnvironmentResponse
    django__get_project_info: _django_pb2.GetProjectInfoResponse
    error: Error
    def __init__(self, check__health: _Optional[_Union[_check_pb2.HealthResponse, _Mapping]] = ..., check__geodjango_prereqs: _Optional[_Union[_check_pb2.GeoDjangoPrereqsResponse, _Mapping]] = ..., python__get_environment: _Optional[_Union[_python_pb2.GetEnvironmentResponse, _Mapping]] = ..., django__get_project_info: _Optional[_Union[_django_pb2.GetProjectInfoResponse, _Mapping]] = ..., error: _Optional[_Union[Error, _Mapping]] = ...) -> None: ...

class Error(_message.Message):
    __slots__ = ("code", "message", "traceback")
    class Code(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        UNKNOWN: _ClassVar[Error.Code]
        INVALID_REQUEST: _ClassVar[Error.Code]
        PYTHON_ERROR: _ClassVar[Error.Code]
        DJANGO_ERROR: _ClassVar[Error.Code]
    UNKNOWN: Error.Code
    INVALID_REQUEST: Error.Code
    PYTHON_ERROR: Error.Code
    DJANGO_ERROR: Error.Code
    CODE_FIELD_NUMBER: _ClassVar[int]
    MESSAGE_FIELD_NUMBER: _ClassVar[int]
    TRACEBACK_FIELD_NUMBER: _ClassVar[int]
    code: Error.Code
    message: str
    traceback: str
    def __init__(self, code: _Optional[_Union[Error.Code, str]] = ..., message: _Optional[str] = ..., traceback: _Optional[str] = ...) -> None: ...
