[package]
name = "djls-ast"
version = "0.0.0"
edition = "2021"

[dependencies]
serde = { workspace = true }

thiserror = "2.0.6"

[dev-dependencies]
insta = { version = "1.41.1", features = ["yaml"] }

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
