# WARNING: This file is generated by protobuf. DO NOT EDIT!
# Any changes made to this file will be overwritten when the protobuf files are regenerated.
# Source: v1/python.proto

from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar, Iterable as _Iterable, Mapping as _Mapping, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class ReleaseLevel(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    ALPHA: _ClassVar[ReleaseLevel]
    BETA: _ClassVar[ReleaseLevel]
    CANDIDATE: _ClassVar[ReleaseLevel]
    FINAL: _ClassVar[ReleaseLevel]
ALPHA: ReleaseLevel
BETA: ReleaseLevel
CANDIDATE: ReleaseLevel
FINAL: ReleaseLevel

class Python(_message.Message):
    __slots__ = ("os", "site", "sys", "sysconfig")
    OS_FIELD_NUMBER: _ClassVar[int]
    SITE_FIELD_NUMBER: _ClassVar[int]
    SYS_FIELD_NUMBER: _ClassVar[int]
    SYSCONFIG_FIELD_NUMBER: _ClassVar[int]
    os: Os
    site: Site
    sys: Sys
    sysconfig: Sysconfig
    def __init__(self, os: _Optional[_Union[Os, _Mapping]] = ..., site: _Optional[_Union[Site, _Mapping]] = ..., sys: _Optional[_Union[Sys, _Mapping]] = ..., sysconfig: _Optional[_Union[Sysconfig, _Mapping]] = ...) -> None: ...

class Os(_message.Message):
    __slots__ = ("environ",)
    class EnvironEntry(_message.Message):
        __slots__ = ("key", "value")
        KEY_FIELD_NUMBER: _ClassVar[int]
        VALUE_FIELD_NUMBER: _ClassVar[int]
        key: str
        value: str
        def __init__(self, key: _Optional[str] = ..., value: _Optional[str] = ...) -> None: ...
    ENVIRON_FIELD_NUMBER: _ClassVar[int]
    environ: _containers.ScalarMap[str, str]
    def __init__(self, environ: _Optional[_Mapping[str, str]] = ...) -> None: ...

class Site(_message.Message):
    __slots__ = ("packages",)
    class PackagesEntry(_message.Message):
        __slots__ = ("key", "value")
        KEY_FIELD_NUMBER: _ClassVar[int]
        VALUE_FIELD_NUMBER: _ClassVar[int]
        key: str
        value: Package
        def __init__(self, key: _Optional[str] = ..., value: _Optional[_Union[Package, _Mapping]] = ...) -> None: ...
    PACKAGES_FIELD_NUMBER: _ClassVar[int]
    packages: _containers.MessageMap[str, Package]
    def __init__(self, packages: _Optional[_Mapping[str, Package]] = ...) -> None: ...

class Sys(_message.Message):
    __slots__ = ("debug_build", "dev_mode", "is_venv", "abiflags", "base_prefix", "default_encoding", "executable", "filesystem_encoding", "implementation_name", "platform", "prefix", "builtin_module_names", "dll_paths", "path", "version_info")
    DEBUG_BUILD_FIELD_NUMBER: _ClassVar[int]
    DEV_MODE_FIELD_NUMBER: _ClassVar[int]
    IS_VENV_FIELD_NUMBER: _ClassVar[int]
    ABIFLAGS_FIELD_NUMBER: _ClassVar[int]
    BASE_PREFIX_FIELD_NUMBER: _ClassVar[int]
    DEFAULT_ENCODING_FIELD_NUMBER: _ClassVar[int]
    EXECUTABLE_FIELD_NUMBER: _ClassVar[int]
    FILESYSTEM_ENCODING_FIELD_NUMBER: _ClassVar[int]
    IMPLEMENTATION_NAME_FIELD_NUMBER: _ClassVar[int]
    PLATFORM_FIELD_NUMBER: _ClassVar[int]
    PREFIX_FIELD_NUMBER: _ClassVar[int]
    BUILTIN_MODULE_NAMES_FIELD_NUMBER: _ClassVar[int]
    DLL_PATHS_FIELD_NUMBER: _ClassVar[int]
    PATH_FIELD_NUMBER: _ClassVar[int]
    VERSION_INFO_FIELD_NUMBER: _ClassVar[int]
    debug_build: bool
    dev_mode: bool
    is_venv: bool
    abiflags: str
    base_prefix: str
    default_encoding: str
    executable: str
    filesystem_encoding: str
    implementation_name: str
    platform: str
    prefix: str
    builtin_module_names: _containers.RepeatedScalarFieldContainer[str]
    dll_paths: _containers.RepeatedScalarFieldContainer[str]
    path: _containers.RepeatedScalarFieldContainer[str]
    version_info: VersionInfo
    def __init__(self, debug_build: bool = ..., dev_mode: bool = ..., is_venv: bool = ..., abiflags: _Optional[str] = ..., base_prefix: _Optional[str] = ..., default_encoding: _Optional[str] = ..., executable: _Optional[str] = ..., filesystem_encoding: _Optional[str] = ..., implementation_name: _Optional[str] = ..., platform: _Optional[str] = ..., prefix: _Optional[str] = ..., builtin_module_names: _Optional[_Iterable[str]] = ..., dll_paths: _Optional[_Iterable[str]] = ..., path: _Optional[_Iterable[str]] = ..., version_info: _Optional[_Union[VersionInfo, _Mapping]] = ...) -> None: ...

class VersionInfo(_message.Message):
    __slots__ = ("major", "minor", "micro", "releaselevel", "serial")
    MAJOR_FIELD_NUMBER: _ClassVar[int]
    MINOR_FIELD_NUMBER: _ClassVar[int]
    MICRO_FIELD_NUMBER: _ClassVar[int]
    RELEASELEVEL_FIELD_NUMBER: _ClassVar[int]
    SERIAL_FIELD_NUMBER: _ClassVar[int]
    major: int
    minor: int
    micro: int
    releaselevel: ReleaseLevel
    serial: int
    def __init__(self, major: _Optional[int] = ..., minor: _Optional[int] = ..., micro: _Optional[int] = ..., releaselevel: _Optional[_Union[ReleaseLevel, str]] = ..., serial: _Optional[int] = ...) -> None: ...

class Sysconfig(_message.Message):
    __slots__ = ("data", "include", "platinclude", "platlib", "platstdlib", "purelib", "scripts", "stdlib")
    DATA_FIELD_NUMBER: _ClassVar[int]
    INCLUDE_FIELD_NUMBER: _ClassVar[int]
    PLATINCLUDE_FIELD_NUMBER: _ClassVar[int]
    PLATLIB_FIELD_NUMBER: _ClassVar[int]
    PLATSTDLIB_FIELD_NUMBER: _ClassVar[int]
    PURELIB_FIELD_NUMBER: _ClassVar[int]
    SCRIPTS_FIELD_NUMBER: _ClassVar[int]
    STDLIB_FIELD_NUMBER: _ClassVar[int]
    data: str
    include: str
    platinclude: str
    platlib: str
    platstdlib: str
    purelib: str
    scripts: str
    stdlib: str
    def __init__(self, data: _Optional[str] = ..., include: _Optional[str] = ..., platinclude: _Optional[str] = ..., platlib: _Optional[str] = ..., platstdlib: _Optional[str] = ..., purelib: _Optional[str] = ..., scripts: _Optional[str] = ..., stdlib: _Optional[str] = ...) -> None: ...

class Package(_message.Message):
    __slots__ = ("dist_name", "dist_version", "dist_editable", "dist_entry_points", "dist_location", "dist_requires", "dist_requires_python")
    DIST_NAME_FIELD_NUMBER: _ClassVar[int]
    DIST_VERSION_FIELD_NUMBER: _ClassVar[int]
    DIST_EDITABLE_FIELD_NUMBER: _ClassVar[int]
    DIST_ENTRY_POINTS_FIELD_NUMBER: _ClassVar[int]
    DIST_LOCATION_FIELD_NUMBER: _ClassVar[int]
    DIST_REQUIRES_FIELD_NUMBER: _ClassVar[int]
    DIST_REQUIRES_PYTHON_FIELD_NUMBER: _ClassVar[int]
    dist_name: str
    dist_version: str
    dist_editable: bool
    dist_entry_points: str
    dist_location: str
    dist_requires: _containers.RepeatedScalarFieldContainer[str]
    dist_requires_python: str
    def __init__(self, dist_name: _Optional[str] = ..., dist_version: _Optional[str] = ..., dist_editable: bool = ..., dist_entry_points: _Optional[str] = ..., dist_location: _Optional[str] = ..., dist_requires: _Optional[_Iterable[str]] = ..., dist_requires_python: _Optional[str] = ...) -> None: ...
