[build-system]
requires = ["uv_build>=0.7.21,<0.8"]
build-backend = "uv_build"

[project]
authors = [
  { name = "Josh Thomas", email = "josh@joshthomas.dev" }
]
dependencies = []
name = "djls-inspector"
requires-python = ">=3.9"
version = "0.1.0"
