name: lint

on:
  pull_request:
  push:
    branches: [main]
  workflow_call:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  FORCE_COLOR: "1"
  PYTHONUNBUFFERED: "1"
  UV_VERSION: "0.4.x"

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: ${{ env.UV_VERSION }}

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-1|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: pre-commit
        run: |
          SKIP=no-commit-to-branch \
          uv run --with pre-commit-uv pre-commit run \
            --all-files \
            --show-diff-on-failure \
            --color always
